### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by GDWR** [python-discord/pixels#85]
I was tryna make an Angular implementation for a moderation tool, so we can hover over pixels to gather meta data.

Angular was asking for CORs headers and making OPTION requests, this currently isn't supported by the PixelsApi. If it was, development for this implementation and other user's who want to use this style of request would be easier.

**Comment by Artemis21** [comment]
I would like to see this too, and FastAPI makes it really easy - https://fastapi.tiangolo.com/tutorial/cors/. I could make a PR if it would get merged?

**Comment by jb3** [comment]
We're open to a PR. However, CORS should not be supported on the set_pixel endpoint.

**Comment by Artemis21** [comment]
Ok. So maybe if it only allows the `GET`, `HEAD` and `OPTIONS` methods?

**Comment by jb3** [comment]
I think it'd be better just to restrict it to certain endpoints, and disable it for /set_pixels

**Comment by Artemis21** [comment]
This is more complicated to do using FastAPI built-in CORS support, because it requires having different middleware for different endpoints - see https://github.com/tiangolo/fastapi/issues/1174.

Why do you think it would be better to do it per-endpoint? To me it seems to make more sense to do it per-method: `GET`, `HEAD` and `OPTIONS` are [*safe*](https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP) methods - they do not alter the state of the server\*, and presumably that is what distinguishes endpoints you are happy to support CORS from endpoints you are not.

**Comment by jb3** [comment]
Gotcha, yeah, complexity is a good point.

Only supporting certain methods sounds fine in that case :+1:
